GET http://localhost:3000/public HTTP/1.1


###
GET http://localhost:3000/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDI3NzYzMTYsInVzZXJfaWQiOjF9.ixic7AM1iIzwPhjxwkVtRYkU7HZ2yYT-ZIBH90bqOr8



###
GET http://localhost:3000/private/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDI3NzYzMTYsInVzZXJfaWQiOjF9.ixic7AM1iIzwPhjxwkVtRYkU7HZ2yYT-ZIBH90bqOr8

###
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
  "name": "sohail",
  "email": "sohail@gmail.com",
  "password": "sohail"
}


###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "test"
}
